### ISSUE TITLE
Agregar envio de email cuando se registra por primera vez.

### ISSUE THREAD

**Issue by aletorancio** [pgClipfs/proyecto-clip-money-a-g1a#25]
Cuando un usuario se registra, es necesario enviar un email para confirmar registro.

**Comment by wooobotch** [comment]
Está la API andando, queda ver cómo integrarla al botón de submit en el componente de registro (así agarra el mail de ahí).

**Comment by aletorancio** [comment]
Api implementada y funcionando!
